repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.14
  hooks:
    # Ruff linter and ruff formatter are separate checks, run them both
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/allganize/ty-pre-commit
  rev: v0.0.14
  hooks:
    - id: ty-check
      args: [--error-on-warning]
      