"""One-off export of d3-celestial stars/lines into the web viewer bundle."""

from __future__ import annotations

import json
import urllib.request
from pathlib import Path

STARS_URL = "https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/stars.6.json"
LINES_URL = "https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/constellations.lines.json"
OUT = Path(__file__).resolve().parents[1] / "navigator/web_viewer/src/constellation-data.ts"
MAX_STAR_MAG = 4.2


def _fetch(url: str) -> dict:
    with urllib.request.urlopen(url, timeout=60) as response:
        return json.load(response)


def _line_segments(lines_doc: dict) -> list[tuple[float, float, float, float]]:
    segments: list[tuple[float, float, float, float]] = []
    for feature in lines_doc["features"]:
        geometry = feature["geometry"]
        for chain in geometry["coordinates"]:
            for index in range(len(chain) - 1):
                ra0, dec0 = chain[index]
                ra1, dec1 = chain[index + 1]
                segments.append((float(ra0), float(dec0), float(ra1), float(dec1)))
    return segments


def _bright_stars(stars_doc: dict) -> list[tuple[float, float, float]]:
    stars: list[tuple[float, float, float]] = []
    for feature in stars_doc["features"]:
        mag = float(feature["properties"]["mag"])
        if mag > MAX_STAR_MAG:
            continue
        ra, dec = feature["geometry"]["coordinates"]
        stars.append((float(ra), float(dec), mag))
    stars.sort(key=lambda row: row[2])
    return stars


def _format_ts(segments: list[tuple[float, float, float, float]], stars: list[tuple[float, float, float]]) -> str:
    seg_lines = ",\n".join(f"  [{a:.4f}, {b:.4f}, {c:.4f}, {d:.4f}]" for a, b, c, d in segments)
    star_lines = ",\n".join(f"  [{ra:.4f}, {dec:.4f}, {mag:.2f}]" for ra, dec, mag in stars)
    return f"""/** Auto-generated by tests/generate_constellation_sky_data.py — do not edit. */

export type EquatorialDeg = readonly [raDeg: number, decDeg: number];

/** Barycentric equatorial J2000 segments: [ra0, dec0, ra1, dec1] in degrees. */
export const CONSTELLATION_LINE_SEGMENTS: readonly (readonly [number, number, number, number])[] = [
{seg_lines},
];

/** Bright stars: [raDeg, decDeg, magnitude]. */
export const BRIGHT_STARS: readonly (readonly [number, number, number])[] = [
{star_lines},
];
"""


def main() -> None:
    stars_doc = _fetch(STARS_URL)
    lines_doc = _fetch(LINES_URL)
    segments = _line_segments(lines_doc)
    stars = _bright_stars(stars_doc)
    OUT.write_text(_format_ts(segments, stars), encoding="utf-8")
    print(f"Wrote {len(segments)} line segments and {len(stars)} stars to {OUT}")  # noqa: T201


if __name__ == "__main__":
    main()
