/** Keep in sync with `simulate/astronomy/constants.py`. */

export const EARTH_RADIUS_AU = 6371 / 149597870.7;
export const EARTH_ORBIT_RADIUS_AU = 1;
export const CAMERA_DISTANCE_EARTH_RADII = 80;
export const DEFAULT_CAMERA_DISTANCE_AU = CAMERA_DISTANCE_EARTH_RADII * EARTH_RADIUS_AU;
export const SKYBOX_FADE_CAMERA_DISTANCE_ORBIT_MULTIPLE = 10;
export const SKYBOX_FADE_SPAN_ORBIT_RADIUS_MULTIPLE = 30;
export const OBSERVER_VELOCITY_ARROW_LENGTH_EARTH_RADII = 4;
export const ARROW_MESH_LENGTH_AU = OBSERVER_VELOCITY_ARROW_LENGTH_EARTH_RADII * EARTH_RADIUS_AU;
export const ARROW_LENGTH_CAMERA_DISTANCE_FRACTION =
  OBSERVER_VELOCITY_ARROW_LENGTH_EARTH_RADII / CAMERA_DISTANCE_EARTH_RADII;
