import numpy as np
from astropy import units as u

KPC_TO_AU = (1 * u.kpc).to_value(u.au)

# ARON get this from the astropy constants?
REAL_SUN_RADIUS_AU = 695_700 / 149_597_870.7
REAL_EARTH_RADIUS_AU = 6_371 / 149_597_870.7

# SUN_SIZE_EXAGGERATION = 20
# EARTH_SIZE_EXAGGERATION = 20
SUN_SIZE_EXAGGERATION = 1
EARTH_SIZE_EXAGGERATION = 1
GALACTIC_ORBIT_DISTANCE_SCALE = 1e-7
# GALACTIC_ORBIT_DISTANCE_SCALE = 1e-9

EARTH_ORBIT_SEGMENTS = 360 * 5

SUN_RADIUS_AU = REAL_SUN_RADIUS_AU * SUN_SIZE_EXAGGERATION
EARTH_RADIUS_AU = REAL_EARTH_RADIUS_AU * EARTH_SIZE_EXAGGERATION

AXIS_HALF_LENGTH_EARTH_RADII = 2.8
OBSERVER_MARKER_EARTH_RADII = 0.16
CAMERA_DISTANCE_EARTH_RADII = 80
AXIS_HALF_LENGTH_CAMERA_DISTANCE_FRACTION = AXIS_HALF_LENGTH_EARTH_RADII / CAMERA_DISTANCE_EARTH_RADII
AXIS_MIN_TOTAL_LENGTH_EARTH_DIAMETERS = 2
# Pan/zoom sensitivity; keep near the solar-system scale, not galactic bounds.
TRACKBALL_SCALE_AU = 2.0
GALACTIC_AXIS_HALF_LENGTH_ORBIT_FRACTION = 0.05
GALACTIC_CENTER_RADIUS_ORBIT_FRACTION = 0.003

# Default Trimesh z_near is 0.01 AU, larger than exaggerated Earth (~0.0009 AU).
CAMERA_Z_NEAR_EARTH_RADII = 0.01
# z_far = camera distance + scene.scale * this multiplier (see _camera_clip_planes).
CAMERA_Z_FAR_SCENE_SCALE_MULTIPLIER = 2.0
# gluPerspective rejects extreme z_far / z_near ratios (~1e8 at true scale).
MAX_DEPTH_RATIO = 5e7
# macOS OpenGL rejects z_near below ~1e-5 AU.
OPENGL_Z_NEAR_MIN_AU = 1e-5

EARTH_ORBIT_COLOR = [180, 180, 200, 255]
YEAR_BOUNDARY_COLOR = [255, 220, 80, 255]
SUN_COLOR = [255, 210, 60, 255]
AXIS_COLOR = [220, 60, 60, 255]
OBSERVER_COLOR = [255, 80, 40, 255]
GALACTIC_ORBIT_COLOR = [120, 80, 180, 255]
GALACTIC_AXIS_COLOR = [180, 120, 255, 255]
GALACTIC_CENTER_COLOR = [240, 200, 255, 255]
LABEL_OFFSET_BODY_RADII = 2.5
LABEL_FONT_SIZE = 18
FPS_LABEL_MARGIN = 8
LINE_WIDTH_PIXELS = 1

MILKY_WAY_FRAME = "milky_way"
SOLAR_SYSTEM_FRAME = "solar_system"
EARTH_CENTER_FRAME = "earth_center"
ROOT_FRAME = "root_frame"
EARTH_CENTER_ORIGIN = np.zeros(3)

ANIMATION_CALLBACK_PERIOD = 1.0 / 60.0
ORBIT_UPDATE_INTERVAL = 10 * u.day
